### ISSUE TITLE
求助,导入项目失败!!!

### ISSUE THREAD

**Issue by lydlovezjr** [lamster2018/EasyProtector#12]
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;

**Comment by lamster2018** [comment]
这个库是novada，用来上传到bintray仓库的东西。位置在project级别gradle文件的  dependencies里，
你看下网络是否正常，sync一下？

如果是正常使用，在你项目module级别的gradle 里 implementation 'com.lahm.library:easy-protector-release:latest.release'就行
