### ISSUE TITLE
夜神模拟器5.1.1版本和7.1.2版本检测模拟器错误,天天模拟器6.0.1检测模拟器错误!!!

### ISSUE THREAD

**Issue by lydlovezjr** [lamster2018/EasyProtector#14]
夜神511 
ceshi start||aosp_shamu-user|universal8895|msm8084|2:cpu:/
    1:cpuacct:/uid_10031/pid_3267
    |end
夜神712
ceshi start||dream2qltezh-user|msm8998|msm8998|2:cpu:/
    1:cpuacct:/uid_10037/pid_3573
    |end
天天601	
emulatorInfo:ceshi start||hlteatt-userdebug|DUK-AL20|Hi6210sft|2:cpu:/
    1:cpuacct:/uid_10033/pid_1668
    |end

**Comment by lydlovezjr** [comment]
老哥,求给个回复呀!!!

**Comment by lamster2018** [comment]
新版解决了
