### ISSUE TITLE
android 自带的虚拟机9.0检测不出来

### ISSUE THREAD

**Issue by Blaite** [lamster2018/EasyProtector#16]
android 自带的虚拟机9.0检测不出来。打印了检测的日志如下：
isEmulator --- >baseBandVersion 1.0.0.0 
     buildFlavor sdk_gphone_x86-user
     productboard goldfish_x86
     boardplatform  
     filter 2:cpu:/
    1:cpuacct:/uid_10091/pid_2675
希望能够尽快适配

**Comment by lamster2018** [comment]
我用自带的模拟器API 28 ，检测是模拟器的呀
ceshi start|1.0.0.0|sdk_gphone_x86-user|goldfish_x86||2:cpu:/
suspectCount = 4
