### ISSUE TITLE
题外话，关于检测模拟器判断

### ISSUE THREAD

**Issue by zhangliangming** [lamster2018/EasyProtector#19]
pm list package 。 因为大部分手机会有一个”是否允许应用读取手机应用列表”的权限，不知这个pm list package 和权限是否有关联。

**Comment by lamster2018** [comment]
”是否允许应用读取手机应用列表”的权限，pm list package跟packageManager拿应用列表信息，不都是一个套路么？

**Comment by zhangliangming** [comment]
@lamster2018 这样子的话，如果到时模拟器把这个权限关闭了，那对判断是否是模拟器的方法，是否有影响？

**Comment by lamster2018** [comment]
如果按照这个逻辑分析，是会影响的，影响就是 『认为没有安装软件，那么嫌疑指数+1』

**Comment by lamster2018** [comment]
能麻烦给一下log么？

**Comment by lamster2018** [comment]
@prookiee  用public boolean readSysProperty(Context context, EmulatorCheckCallback callback)
这个api，可以检测夜神6.2.6.0
