### ISSUE TITLE
oppo R7 虚拟机检测 有时候会把真机判断为虚拟机。概率事件

### ISSUE THREAD

**Issue by guoleifei** [lamster2018/EasyProtector#2]
oppo R7 虚拟机检测 有时候会把真机判断为虚拟机。概率事件
不好复现

**Comment by guoleifei** [comment]
这个比较尴尬。我这也没这个机器 用的云真机 。
客户先发现的。然后我用的云真机 打包上去 第一次是显示虚拟机。第二次和后面几次都正常。
我这就我自己的手机，没测试机这个比较悲剧

**Comment by lamster2018** [comment]
云真机啊....这个就比较尴尬了。因为我不确定云真机的机器刷了他们自制的rom没有。
而且从你的描述“只有第一次显示虚拟机，后续正常”，按道理同一部机器结果是一样的，因为读取的东西都是一样的，会不会是云真机的问题？

还有，客户反馈的机型是oppo r7出问题，这个你能想办法抓取log么？

**Comment by guoleifei** [comment]
我试试。 看看他那还出不。如果出的话 我到时候给他个包试试。看看能不能搞出来。

**Comment by guoleifei** [comment]
gsm.version.baseband=MOLY.LR9.W1423.MD.LWTG.CMCC.MP.V10.P70, 2016/01/21 20:07 
ro.build.flavor= 
ro.product.board=oppo6752_15021 
ro.board.platform= 
cat /proc/self/cgroup=2:cpu:/ 1:cpuacct:/uid/10172

这个是他手机返回的数据

**Comment by lamster2018** [comment]
baseband有
flavor没有+1
board有
platform没有+1
我原本是想在两者都有值的情况下进行等价判断的，问题出在board和platform的比较上，platform的值是""而不是null，所以最后还是进行了判断。+1
cgroup有
所以最后嫌疑指数为3，判断为虚拟机。
你如果紧急要用这个库上线的话，你把
```
 if (productBoard != null && boardPlatform != null && !productBoard.equals(boardPlatform))
            ++suspectCount;
```
改成
```
        if (!TextUtils.isEmpty(productBoard) 
                && !TextUtils.isEmpty(boardPlatform) 
                && !productBoard.equals(boardPlatform))
            ++suspectCount;
```
试一试

**Comment by guoleifei** [comment]
昨天已经上线了。直接copy了一份那个方法
修改了下空判断

 fun readSysProperty(): Boolean {
        var suspectCount = 0

        val basebandVersion = CommandUtil.getSingleInstance().getProperty("gsm.version.baseband")
        if (basebandVersion.isNullOrEmpty()) ++suspectCount

        val buildFlavor = CommandUtil.getSingleInstance().getProperty("ro.build.flavor")
        if (buildFlavor.isNullOrEmpty() or (buildFlavor != null && buildFlavor.contains("vbox")))
            ++suspectCount

        val productBoard = CommandUtil.getSingleInstance().getProperty("ro.product.board")
        if (productBoard.isNullOrEmpty()) ++suspectCount

        val boardPlatform = CommandUtil.getSingleInstance().getProperty("ro.board.platform")
        if (boardPlatform.isNullOrEmpty()) ++suspectCount
//        if ((boardPlatform == null) or ("" == boardPlatform)) ++suspectCount

        if (!productBoard.isNullOrEmpty() && !boardPlatform.isNullOrEmpty() && productBoard != boardPlatform)
            ++suspectCount

        val filter = CommandUtil.getSingleInstance().exec("cat /proc/self/cgroup")
        if (filter == null || filter.isEmpty()) ++suspectCount

        return suspectCount > 2
    }

**Comment by lamster2018** [comment]
嗯，我这边也修了这个，谢谢
