### ISSUE TITLE
检测夜神模拟器6.2.6.0失效

### ISSUE THREAD

**Issue by pengjunhong** [lamster2018/EasyProtector#20]
ceshi start|null|null|sdm660|msm8084|qcom|support CameraFlash|sensorNum7|userAppNum3|2:cpu:/apps
1:cpuacct:/uid/10028

**Comment by pengjunhong** [comment]
![12](https://user-images.githubusercontent.com/18617995/50441166-56c1c680-0934-11e9-945a-a619558dd3e6.png)

**Comment by lamster2018** [comment]
夜神牛啤，6.2.6搞事情了，行，我这边记下了

**Comment by pengjunhong** [comment]
@lamster2018 
/**
     * 判断是否存在光传感器来判断是否为模拟器
     * 部分真机也不存在温度和压力传感器。其余传感器模拟器也存在。
     * @return true 为模拟器
     */
    public static Boolean notHasLightSensorManager(Context context) {
        SensorManager sensorManager = (SensorManager) context.getSystemService(Context.SENSOR_SERVICE);
        Sensor sensor8 = sensorManager.getDefaultSensor(Sensor.TYPE_LIGHT); //光
        if (null == sensor8) {
            return true;
        } else {
            return false;
        }
    }
这个可行。在获取传感器的个数时，指定需要有光传感器，如果没有 则指数+1.

**Comment by lamster2018** [comment]
我刚刚运行了一下夜神6.2.6.0030版本，检测为模拟器，你的方案我已经记下了
![image.png](https://upload-images.jianshu.io/upload_images/2554175-99b08f2a08bd6244.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by amber-yi** [comment]
我用真机测试的时候，也会发现没有光传感器，型号三星SM-J3300

**Comment by lamster2018** [comment]
看来这个方法也有一定缺陷。是否增加光传感器的条目我再思考一下。

**Comment by lany192** [comment]
根据光传感器判断很有用，不过的确有部分手机没有光传感器，通常是之前的老版本的低端手机和部分中端手机。可以考虑下：1.光传感器判断增加系统版本判断，低于4.4不检测 。2.增加cpu型号来加强判断光传感器

**Comment by Guowj** [comment]
/**
 * 判断蓝牙是否有效来判断是否为模拟器
 *
 * @return true 为模拟器
 */
public boolean notHasBlueTooth() {
    BluetoothAdapter ba = BluetoothAdapter.getDefaultAdapter();
    if (ba == null) {
        return true;
    } else {
        // 如果有蓝牙不一定是有效的。获取蓝牙名称，若为null 则默认为模拟器
        String name = ba.getName();
        if (TextUtils.isEmpty(name)) {
            return true;
        } else {
            return false;
        }
    }
}
--------------------- 
作者：秋名山小尼玛 
来源：CSDN 
原文：https://blog.csdn.net/tianshuai4317618/article/details/78834683 
版权声明：本文为博主原创文章，转载请附上博文链接！

判断蓝牙比较靠谱。

**Comment by lamster2018** [comment]
@Guowj 这个蓝牙的我之前考虑过了，如果用户在关闭蓝牙的情况下，是拿不到蓝牙的信息的，而且我也不想加入蓝牙的权限。思路可以，共同进步老铁~

**Comment by tomUp** [comment]
该库已更新至v1.1.1，issue先关闭了，后续有问题再提~
