### ISSUE TITLE
检测雷电模拟器3.4.3失效

### ISSUE THREAD

**Issue by Harreke** [lamster2018/EasyProtector#21]
![image](https://user-images.githubusercontent.com/8429287/50482418-5e12ce00-0a21-11e9-9b37-2c39fffd4140.png)
ceshi start|null|android_x86-user|f100|android-x86|android_x86|supportCameraFlash|sensorNum6|userAppNum5|2:cpu:/1:cpuacct:/uid_10031/pid_3009|end
具体情况为：
安装了4个app时，检测正常；又安装了一个app后检测失效

**Comment by lamster2018** [comment]
看来我那个通过 userApp的检测条目有缺陷

**Comment by Harreke** [comment]
发现一个现象：

**Comment by lamster2018** [comment]
额，这笔问题，这位老铁新开一个issue，提个log试一下~不然楼上那位老铁一脸懵逼的

**Comment by Harreke** [comment]
是否可以从这里考虑？比方说，某一apk只能在armv7上运行，但经过检测却发现cpu核心是x86的，是否就可以增加模拟器判定嫌疑度？

**Comment by lamster2018** [comment]
额，这个emmmmm，我没有太理解

**Comment by lamster2018** [comment]
嗯嗯嗯，这个思路可以

**Comment by Harreke** [comment]
在x86的pc上跑armv7核心的模拟器速度十分难以忍受，所以貌似主流模拟器的核心都是x86，然后用某种方法模拟优化成了armv7的核心？

**Comment by tomUp** [comment]
该库已更新至v1.1.1，issue先关闭了，建议已经关联到#57

**Comment by qinlili23333** [comment]
> 是否可以从这里考虑？比方说，某一apk只能在armv7上运行，但经过检测却发现cpu核心是x86的，是否就可以增加模拟器判定嫌疑度？

zenfone2和小米平板2，以及fyde os等一众android x86都会被误杀
