### ISSUE TITLE
空指针错误（Attempt to invoke interface method 'void com.lahm.library.VirtualCheckCallback.findSuspect()' on a null object reference））

### ISSUE THREAD

**Issue by Harreke** [lamster2018/EasyProtector#23]
![image](https://user-images.githubusercontent.com/8429287/50593895-4c27a400-0ed5-11e9-8582-460c24f2a8f8.png)
突然产生了大量空指针问题，貌似都是发生在按back键退出app的时候发生的
崩溃率很大，可否尽快加入非空判断？

是在Application初始化时调用的，具体kotlin代码如下：

`if (ProcessUtil.isMainProcess(application)) {`
`    VirtualApkCheckUtil.getSingleInstance().checkByPortListening(application.packageName) {`
`        Log.e("Application", "find multiapp suspect")`
`        DeviceInfo = generateDeviceInfo(application, true)`
`    }`
`}`

**Comment by lamster2018** [comment]
我代码逻辑里有一段， 检测后会把listener置空的操作

**Comment by lamster2018** [comment]
『先启动App（记为A1），再多开（记为A2），A1或者A2检测到多开后，就把listener清空了』----这一步没问题

『这时候再进行一次多开，那么A1、A2就有可能再次尝试调用findSuspect()回调而遇到而发生空指针错误』----如果还进行多开，那不就正好空指针崩溃么？

这样吧，我这几天把逻辑改一下，把callback全部交给开发者自己处理，我不清空了。
