### ISSUE TITLE
夜神模拟器6.1.0.1版本检测失败，用的1.0.5版本；

### ISSUE THREAD

**Issue by rx9158** [lamster2018/EasyProtector#24]
![_20190104153043](https://user-images.githubusercontent.com/8063752/50677737-85c3f080-1036-11e9-8d8f-e7b038ac9553.png)

**Comment by lamster2018** [comment]
年前赶进度，会尽快修改

**Comment by rx9158** [comment]
之前就是用带content的方法执行的；　　　　　然后这边在1.0.5基础上，加了一个是否能跳转到拨号页面的判断 (根据模拟器打不了电话来猜测的)；　测了下好像可以用，还没有大面积测试；　请问是否可行？

**Comment by lamster2018** [comment]
加了一个是否能跳转到拨号页面的判断 (根据模拟器打不了电话来猜测的)
-------
1.这个思路可以；
2.跳到拨号页面，这个行为会不会引起用户疑惑？

**Comment by tomUp** [comment]
该库已更新至v1.1.1，issue先关闭了，后续有问题再提~
