### ISSUE TITLE
基于Socket，真正的一行代码检测多开哦

### ISSUE THREAD

**Issue by wangkunlin** [lamster2018/EasyProtector#25]
```java
public class App extends Application {

    LocalServerSocket mServerSocket;

    @Override
    public void onCreate() {
        super.onCreate();
        try {
            // 借鉴自 AMS 与 zygote 通信
            mServerSocket = new LocalServerSocket(getPackageName());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
```
不需要开线程，不需要遍历端口，只需要一个唯一确定的名字即可。唯一的缺点是多开的 app 之间无法通信，是因为 SELinux 的保护机制限制了文件访问权限

**Comment by lamster2018** [comment]
诶这个点子好，我忙完工作我试一下。

**Comment by wangkunlin** [comment]
> 诶这个点子好，我忙完工作我试一下。

方案可行么？我手上只有小米，是可以检测的，其他的不清楚

**Comment by lamster2018** [comment]
小老板你们年底不用加班赶进度么？？？？？我一直在加班，还没试

**Comment by wangkunlin** [comment]
年底不是都没事做么？你们怎么还加起班了。。。

**Comment by lamster2018** [comment]
一言难尽，说来话长，等我忙完，我看看这个，这个api我以前没接触过，我很有兴趣

**Comment by myfGitup** [comment]
这个方法我试过了，来说下感受，真的挺好的，魅族手机自己带的应用分身，直接不能打开应用了，阻止了90%的分身软件制作分身，但是有一款应用很牛逼，多开分身，这个软件依旧能制作并成功打开软件，求助

**Comment by wangkunlin** [comment]
@myfGitup 多个方案综合起来用呗。另外你说的那个非常nb的多开是哪个应用啊。

**Comment by spiritzore** [comment]
多开检测，hook了getPackageName()方法，导致返回的包名不正确，所以是没有用的

**Comment by wangkunlin** [comment]
那换一个 固定的字符串呢？不用 packagename.

**Comment by myfGitup** [comment]
> @myfGitup 多个方案综合起来用呗。另外你说的那个非常nb的多开是哪个应用啊。

这个应用的名字叫做  多开分身

**Comment by myfGitup** [comment]
> 那换一个 固定的字符串呢？不用 packagename.

不行，自己指定一个唯一的字符串这个也不能避免多开分身打开分身的应用

**Comment by myfGitup** [comment]
> 那换一个 固定的字符串呢？不用 packagename.

多开分身使用过的是 混沌 chaos 引擎，希望看到的大佬们给出可行方案，避免应用双开

**Comment by lamster2018** [comment]
这个方法已经集成并测试了，比以前的端口检测法好用很多

**Comment by myfGitup** [comment]
能避免多开吗

**Comment by lamster2018** [comment]
搞广义多开还是可以搞

**Comment by lamster2018** [comment]
发布了这个方法，但是我忘记指定这个issue了，我在方法的注释上感谢你了 @wangkunlin

**Comment by lamster2018** [comment]
大家更新一下看有啥问题没，没有我就关闭了

**Comment by huopochuan** [comment]
> 这个方法我试过了，来说下感受，真的挺好的，魅族手机自己带的应用分身，直接不能打开应用了，阻止了90%的分身软件制作分身，但是有一款应用很牛逼，多开分身，这个软件依旧能制作并成功打开软件，求助

哪款应用？

**Comment by Wudelin** [comment]
这个方法如何检测开启多个微信呢

**Comment by wangkunlin** [comment]
@Wudelin 多开检测只是用于自身检测的，不能检测其他 app 的

**Comment by Wudelin** [comment]
麻烦看一下我的另一个issue 关于蓝叠模拟器的
