### ISSUE TITLE
vivo x9s 

### ISSUE THREAD

**Issue by yaolv7** [lamster2018/EasyProtector#3]
大佬，vivo x9s  OS7.1.2   虚拟机、多开检测无效

**Comment by lamster2018** [comment]
虚拟机检测的问题
你能帮忙抓取一下log吗？
see：https://github.com/lamster2018/EasyProtector/issues/2

多开检测的话，我一共提供了5种方法，你用端口检测法能不能生效?
文档里有说其余四种现在被多开软件都针对性的反制了。
能顺便提供一下 是什么多开软件，机型信息么？谢谢。
