### ISSUE TITLE
模拟器是否可以通过判断进程组数量来检测

### ISSUE THREAD

**Issue by Knight-ZXW** [lamster2018/EasyProtector#35]
实测发现夜神模拟器和雷电模拟器 获取进程组信息时，数量都是2 并且类别都是 cpu 和cpuaact。
因此我自己加了判断进程组数量 小于3 则认为有模拟器嫌疑

**Comment by tomUp** [comment]
@Knight-ZXW 
你好，真机也有这种情况~
