### ISSUE TITLE
检测夜神模拟器6.2.8.0失效

### ISSUE THREAD

**Issue by Chenshibiao** [lamster2018/EasyProtector#36]
检测夜神模拟器6.2.8.0失效，用的是1.1.0版本

**Comment by GooDong** [comment]
同失效、v6.2.1.6

**Comment by GooDong** [comment]
> 检测夜神模拟器6.2.8.0失效，用的是1.1.0版本

建议：

if (null == baseBandVersion || baseBandVersion.contains("1.0.0.0"))
            suspectCount += 2;//基带信息

if (sensorSize <= 7) ++suspectCount;//传感器个数

if (userAppSize <= 5) ++suspectCount;//用户安装的app个数

**Comment by Chenshibiao** [comment]
> > 检测夜神模拟器6.2.8.0失效，用的是1.1.0版本
> 
> 建议：
> 
> if (null == baseBandVersion || baseBandVersion.contains("1.0.0.0"))
> suspectCount += 2;//基带信息
> 
> if (sensorSize <= 7) ++suspectCount;//传感器个数
> 
> if (userAppSize <= 5) ++suspectCount;//用户安装的app个数

我按照你的改了，还是检测不出夜神。传感器个数刚好7，用户安装的app个数挺多的，所以这一条没多大意义。

**Comment by GooDong** [comment]
> > > 检测夜神模拟器6.2.8.0失效，用的是1.1.0版本
> > 
> > 
> > 建议：
> > if (null == baseBandVersion || baseBandVersion.contains("1.0.0.0"))
> > suspectCount += 2;//基带信息
> > if (sensorSize <= 7) ++suspectCount;//传感器个数
> > if (userAppSize <= 5) ++suspectCount;//用户安装的app个数
> 
> 我按照你的改了，还是检测不出夜神。传感器个数刚好7，用户安装的app个数挺多的，所以这一条没多大意义。



> > > 检测夜神模拟器6.2.8.0失效，用的是1.1.0版本
> > 
> > 
> > 建议：
> > if (null == baseBandVersion || baseBandVersion.contains("1.0.0.0"))
> > suspectCount += 2;//基带信息
> > if (sensorSize <= 7) ++suspectCount;//传感器个数
> > if (userAppSize <= 5) ++suspectCount;//用户安装的app个数
> 
> 我按照你的改了，还是检测不出夜神。传感器个数刚好7，用户安装的app个数挺多的，所以这一条没多大意义。

那没办法了、只能继续找夜神的其他特征了

**Comment by tomUp** [comment]
@Chenshibiao 该库已更新至v1.1.1，issue先关闭了，后续有问题再提~

@GooDong 你提议的意见，部分已经参考，v1.1.1版本已经更新，感谢~
