### ISSUE TITLE
建议更新检测条件

### ISSUE THREAD

**Issue by GooDong** [lamster2018/EasyProtector#39]
建议：

if (null == baseBandVersion || baseBandVersion.contains("1.0.0.0"))
suspectCount += 2;//基带信息

if (sensorSize <= 7) ++suspectCount;//传感器个数

if (userAppSize <= 5) ++suspectCount;//用户安装的app个数

亲测：夜神，雷电、逍遥、mumu，腾讯手游助手，genymotion有效、

**Comment by lamster2018** [comment]
你提pr

**Comment by tomUp** [comment]
#57
