### ISSUE TITLE
感觉 这么检测不是个事

### ISSUE THREAD

**Issue by guoleifei** [lamster2018/EasyProtector#43]
这里发一个。说不定那边做分身的或者虚拟机的就对应改一个。就跟提BUG一样

**Comment by tomUp** [comment]
检测模拟器，该库的方法是通过嫌疑值来做检测，因为现在没有一些确定的方式可以判断真机还是模拟器，所以也在一直完善和探索，如果有好的建议可以到 #57 里面提出，谢谢！issues先关闭了
