### ISSUE TITLE
少了'x86_64', 'arm64-v8a，需要适配这两个架构了

### ISSUE THREAD

**Issue by azhao-2019** [lamster2018/EasyProtector#49]
打包apk的时候，发现少了'x86_64', 'arm64-v8a这两个架构的编译

**Comment by moz1q1** [comment]
这个，自己把库代码下载，自己加就好

**Comment by lamster2018** [comment]
> 打包apk的时候，发现少了'x86_64', 'arm64-v8a这两个架构的编译

我当时的考虑是，用x86_64的真机好像真的不是很多，armv7也都能被兼容。如果我打了全cpu平台的，有些开发者也不需要。

现在的话，google那边是要求适配arm v8，v8的事情我会再下个版本修。x86_64的不考虑了。

**Comment by lamster2018** [comment]
supportted
