### ISSUE TITLE
分身检测失败

### ISSUE THREAD

**Issue by lizhanqi** [lamster2018/EasyProtector#5]
一款名多开分身的会检测失败,经测试多开分身软件能进行修改机型,地理位置模拟,分身的应用的包名会跟原应用一致

**Comment by lizhanqi** [comment]
发现个规律:多开分身的克隆包名字安装时候是按照dkmodel开头,但是app运行获取的都是自己的包名,可以作为一个检测方式,另外分身大师多开版这个并没有做安装程序,也没有包名信息,一切运行完美全部绕过检测

**Comment by lamster2018** [comment]
非常感谢，不知道你那边的机型，版本和软件版本是怎样的，以下我目前的测试结果，

测试机器/多开软件* | 多开分身6.9 | 平行空间4.0.8389 | 双开助手3.8.4 | 分身大师2.5.1 | VirtualXP0.11.2 | Virtual App *
-- | -- | -- | -- | -- | -- | --
红米3S/Android6.0/原生eng | XXXO | OXOO | OXOO | XOOO | XXXO | XXXO
华为P9/Android7.0/EUI 5.0 root | XXXX | OXOX | OXOX | XOOX | XXXX | XXXO
小米MIX2/Android8.0/MIUI稳定版9.5 | XXXX | OXOX | OXOX | XOOX | XXXX | XXXO
一加5T/Android8.1/氢OS 5.1 稳定版 | XXXX | OXOX | OXOX | XOOX | XXXX | XXXO


可以看到的是，目前狭义检测多开方案基本凉凉。
