### ISSUE TITLE
小米8的手机检测到是夜神模拟器？

### ISSUE THREAD

**Issue by SuperXmx** [lamster2018/EasyProtector#53]
hardware = qcom

**Comment by tomUp** [comment]
> hardware = qcom

可以先把`qcom`这段代码注释看看打印的是什么。

```
    private CheckResult checkFeaturesByHardware() {
        String hardware = getProperty("ro.hardware");
        if (null == hardware) return new CheckResult(RESULT_MAYBE_EMULATOR, null);
        int result;
        String tempValue = hardware.toLowerCase();
        switch (tempValue) {
            case "ttvm"://天天模拟器
            case "nox"://夜神模拟器
            // case "qcom"://夜神模拟器
            case "cancro"://网易MUMU模拟器
            case "intel"://逍遥模拟器
            case "vbox":
            case "vbox86"://腾讯手游助手
            case "android_x86"://雷电模拟器
                result = RESULT_EMULATOR;
                break;
            default:
                result = RESULT_UNKNOWN;
                break;
        }
        return new CheckResult(result, hardware);
    }
```

**Comment by SuperXmx** [comment]
ceshi start|AT4.0.c2.6-301-0802_1245_9b38d41,AT4.0.c2.6-301-0802_1245_9b38d41|dipper-user|sdm845|sdm845|qcom|support CameraFlash|sensorNum52|userAppNum62|6:freezer:/
5:memory:/
4:cpuset:/top-app
3:cpu:/
2:schedtune:/top-app
1:cpuacct:/uid_10237/pid_16629
0::/
|end

**Comment by SuperXmx** [comment]
看数据的话，应该是包含了qcom在里面

**Comment by SuperXmx** [comment]
Test start
hardware = qcom
flavor = dipper-user
model = MI 8
manufacturer = Xiaomi
board = sdm845
platform = sdm845
baseBand = AT4.0.c2.6-301-0802_1245_9b38d41,AT4.0.c2.6-301-0802_1245_9b38d41
sensorNumber = 52
userAppNumber = 62
supportCamera = true
supportCameraFlash = true
supportBluetooth = true
hasLightSensor = true
cgroupResult = 6:freezer:/
5:memory:/
4:cpuset:/top-app
3:cpu:/
2:schedtune:/top-app
1:cpuacct:/uid_10237/pid_16979
0::/

suspectCount = 0

**Comment by tomUp** [comment]
@SuperXmx 
qcom是表示高通的意思，现在v1.1.0没有对这个作为嫌疑值。
v1.1.1还在测试中，不小心合并到了主分支。

**Comment by SuperXmx** [comment]
好的，我只需要切到v1.1.0的tag，应该就是稳定版的是吗

**Comment by tomUp** [comment]
> 好的，我只需要切到v1.1.0的tag，应该就是稳定版的是吗

是的

**Comment by tomUp** [comment]
> 好的，我只需要切到v1.1.0的tag，应该就是稳定版的是吗

源码可以看分支dev_v1.1.1
