### ISSUE TITLE
AS自带模拟器检测失败

### ISSUE THREAD

**Issue by liujianjun93** [lamster2018/EasyProtector#6]
仔细看了模拟器检测部分的代码，发现在对比平台信息和处理信息的时候时当两者都不为空的时候进行判断的，在测试中发现AS自带的模拟器无法检测，具体结果为
基带信息：是
渠道信息：不是
处理器信息：不是
平台信息：是
对比信息：不是
控制信息：不是

整体结果：不是模拟器

个人建议：平台处理器对比时，只要有一个为空就应该再次增加其嫌疑度

![1533517426](https://user-images.githubusercontent.com/22069560/43692252-c1b66ee2-9958-11e8-8d75-30adb2eaf648.png)

**Comment by liujianjun93** [comment]
![1533518084](https://user-images.githubusercontent.com/22069560/43692966-fd331420-995d-11e8-9758-e079193e2c95.png)

**Comment by lamster2018** [comment]
好的，谢谢，我待会儿改

**Comment by lamster2018** [comment]
你好，我想了一下你的建议
[平台处理器对比时，只要有一个为空就应该再次增加其嫌疑度]

因为单独对平台，处理器对比的时候就做了空值判断，嫌疑指数+1，
合并对比的时候，有一个空值就+1，容易产生误判。
有部分老版本真机，平台参数为“”，这样单独判断和合并判断的嫌疑指数就已经为2了，很容易误判。

我觉得还是在
1.优化单独判断
2.增加优化单独判断项

上去改进模拟器检测方案。
谢谢你的支持。

**Comment by liujianjun93** [comment]
你好，如果我没理解错的话，原来的意思是【嫌疑指数为2】就判断为模拟器，但是我在代码中发现
return suspectCount > 2;
想问下这里是不是有小问题呢？
是否应该写为return suspectCount > =2;？
所以我才提出了增加嫌疑度的建议

祝顺利！

**Comment by liujianjun93** [comment]
嗯嗯 ，我明白了！谢谢！
