### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by lk4403** [lamster2018/EasyProtector#61]
库版本：v1.1.0
系统版本：
手机型号：
问题详情、异常提示：
java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
代码定位：
com.lahm.library.EmulatorCheckUtil 

private int getUserAppNum(String userApps) {
        *** String[] result = userApps.split("package:"); ***
        return result.length;
    }

**Comment by lamster2018** [comment]
1.1.1我已经修了这个bug
