### ISSUE TITLE
关于最新的模拟器检测只会回调Info，如何根据这些参数判断是否为模拟器

### ISSUE THREAD

**Issue by q248345703** [lamster2018/EasyProtector#63]
不知道作者是如何判断的，不过只是单纯的回调这些Info的话。我们好像也挺难判断是否为模拟器，因为没有一个合格或者已知的指标。希望作者可以指示一下

**Comment by lamster2018** [comment]
EmulatorUtil. readSysProperty 方法，返回值是boolean，可以拿这个粗略判断，回调参数拿info是方便你们打印上报。

**Comment by q248345703** [comment]
非常感谢回复，当时一开始没看源代码，钻了牛角尖，才发了这样issue。后来已经解决了并关闭了issue。谢谢作者。刚好反馈一个bug，三星第三方极光Rom已Root，但是用该库测试显示的是未Root。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Volatile"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 上午9:51
收件人:&nbsp;"lamster2018/EasyProtector"<EasyProtector@noreply.github.com&gt;;
抄送:&nbsp;"白丶马非马"<248345703@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [lamster2018/EasyProtector] 关于最新的模拟器检测只会回调Info，如何根据这些参数判断是否为模拟器 (#63)




EmulatorUtil. readSysProperty 方法，返回值是boolean，可以拿这个粗略判断，回调参数拿info是方便你们打印上报。
