### ISSUE TITLE
夜神模拟器  EasyProtectorLib.checkIsRunningInEmulator() 未检测出

### ISSUE THREAD

**Issue by guoleifei** [lamster2018/EasyProtector#7]
数据
ceshi start||dream2qltezh-user|SM-G955F|msm8998|2:cpu:/
    1:cpuacct:/uid_10037/pid_4060
    |end

**Comment by lamster2018** [comment]
请问一下是夜神哪个版本？我测试的时候好像还能检测的

**Comment by guoleifei** [comment]
v_6.2.1.6

**Comment by liujianjun93** [comment]
我这里夜神v_6.2.1.6 最新版可以检测的...

**Comment by guoleifei** [comment]
你试一下他那个android 7.1的模拟器。5.0的能检测出来

**Comment by lamster2018** [comment]
感谢楼上两位老铁一直在跟这笔问题。
库检测我觉得是时候增加几个独立判断项了

**Comment by guoleifei** [comment]
没辙。。我们是考勤软件-- 现在作弊的太多了-- 要求加验证 严格意义上说  分身软件、虚拟机什么的都不让用的。

**Comment by mixin716** [comment]
@liujianjun93 兄弟你现在都是用什么检测方法呢

**Comment by lamster2018** [comment]
我自己项目里集成了，然后收集机器数据大概1w+，近期准备加新的判断条件

**Comment by guoleifei** [comment]
坑啊--我们项目的后台人家打算 反作弊全扔给客户端了

**Comment by lamster2018** [comment]
可以，很感动

**Comment by guoleifei** [comment]
最近又被拉出来搞这个了--说反应太多了。
要加上在虚拟机或者分身软件的打卡提示。之前没加只是反馈了后台。
看到之前写过一个逻辑就是比对跟自己app名称类似的app有几个超过一个就是-这个不是很靠谱。但是姑且算一个条件。

**Comment by guoleifei** [comment]
今天被逼又想出一个主意 用app中执行shell 根据一些信息判断。但是不知道可行不可行。
有空一起折腾下。我这没测试机。。

**Comment by lamster2018** [comment]
1.0.5解决了

**Comment by guoleifei** [comment]
我前一段发现 通过adb shell 打印 activity 栈信息可以用来判断--
但是5.0以上的系统已经不能执行某些命令了
