### ISSUE TITLE
美图手机、小米手机被识别成模拟器了

### ISSUE THREAD

**Issue by xiaokj16** [lamster2018/EasyProtector#8]
美图手机型号Meitu M4，android系统版本是4.4.4，
小米手机具体型号不清楚，android系统版本是4.4.2，

**Comment by lamster2018** [comment]
能看下EmulatorCheckCallback里的输出么

**Comment by zhangliangming** [comment]
美图手机型号Meitu M4，android系统版本是4.4.4。我这边也是被识别成模拟器了。输出如下：
baseBandVersion:MOLY.LR9.W1423.MD.LWTG.CMCC.MP.V15.P16, 2015/04/21 13:37
buildFlavor:
productBoard:
boardPlatform:
filter:2:cpu:/1:cpuacct:/uid/10131

**Comment by lamster2018** [comment]
近期准备加新的判断条件了

**Comment by lamster2018** [comment]
试一下1.0.5

**Comment by lamster2018** [comment]
@xiaokj16 新的方案解决这笔问题了吗？

**Comment by prookiee** [comment]
夜深模拟器  6.2.6.0 被识别成真机

**Comment by lamster2018** [comment]
能给一下log么？？

**Comment by lamster2018** [comment]
@prookiee  用public boolean readSysProperty(Context context, EmulatorCheckCallback callback)
这个api，可以检测夜神6.2.6.0

**Comment by prookiee** [comment]
嗯，这个可以，但是返回值还是false,可以根据callback中的值去判断

**Comment by lamster2018** [comment]
首先感谢你的反馈。其次以后提问题，新开issue，带上log，可以加快解决速度，感谢

**Comment by prookiee** [comment]
好的，以后注意，谢谢
